branches:
  only:
    - develop
    - master
os:
  - linux
  - osx
osx_image: xcode9.3
dist: trusty
language: java
jdk:
  - oraclejdk8
git:
  submodules: false
before_install:
  - sed -i -e 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - cd cello-webapp/
after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$DOCKER_USERNAME" != "" ] && [ "$DOCKER_PASSWORD" != "" ]; then mvn docker:build -B && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && mvn docker:push -B; fi
